### ISSUE TITLE
PiZeroW

### ISSUE THREAD

**Issue by intromatt** [headmelted/codebuilds#27]
I am sorry if this is an ignorant question but is it possible to run Code on a PiZeroW.

I followed the steps but sadly it doesn't open (I can see the icon).

thank you.

**Comment by xshotD** [comment]
It probably would but it probably would be laggy due to memory usage of Electron/VSCode. If you have any other apps open that might be the problem

**Comment by intromatt** [comment]
I followed the setup script and got the icon but sadly the app will not open.  Is there something I may be missing.

Thank you very much for your help.

(If this is a problem I will order a Pi3)..

**Comment by xshotD** [comment]
Try running this:

```
/usr/share/code-oss/code-oss
```

What's the output?

**Comment by intromatt** [comment]
Segmentation fault

I am SSHing and executed the command

**Comment by xshotD** [comment]
I'm on latest build, Pi 3, and have nothing like this.

**Comment by headmelted** [comment]
I suspect it may not be possible to run on the Pi Zero W, at least not yet, I'm afraid.

The Pi Zero W runs on the same Broadcom BCM2835 that the original Pi does - which is ARMv6 rather than ARMv7.

The parts that this project is doing could target ARMv6 easily enough, but Electron targets ARMv7 has a baseline, which is almost certainly what's causing your segmentation faults.

I'm hoping to extend the nightly builds out to libchromiumcontent and Electron so that I can add ARM64 support to the Electron binaries - it will hopefully be possible to also add ARMv6 support at that time - but I have no idea what the timeframe for that will be unfortunately.

_As a side note, even if we get it building, the BCM2835 will almost certainly struggle to run VS Code at a usable speed (single core, low frequency).  I'm still interested in getting it running though for the fun of it. :-)_

**Comment by intromatt** [comment]
Thank you very much for the explanation and everything makes complete sense to me.  Looks like I will just have to order my 6th Pi3.

Cheers from Bulgaria.

**Comment by headmelted** [comment]
Closing this out for now as we're limited in terms of what we can do about it until libchromiumcontent and Electron support more ARM variants

**Comment by intromatt** [comment]
thanx again.
